config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
 
  get '/team', to: "home#team"

  
  get '/test', to: "home#test"


  post '/login', to: "home#login"


  get '/blog', to: "home#blog"
  post '/post', to: "home#post"
  
  
  get '/admin', to: "home#admin"
  post '/newproduct', to: "home#newproduct"

  # routes for viewing and buying products (Products Controller)
  get '/products', to: 'product#index', as: 'storefront'
  get '/products/:id/buy', to: 'product#add_to_cart', as: 'add_to_cart'
  get '/products/cart', to: 'product#view_cart', as: 'view_cart'
  get '/products/checkout', to: 'product#checkout', as: 'checkout'
  get '/products/api', to: 'product#api'
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/cat.rb
class Cat < ApplicationRecord
end

app/models/marketplace.rb
class Marketplace < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
		has_secure_password

		def welcome
				"Hello, #{self.email}"
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    skip_before_action :verify_authenticity_token
    def index
        @marketplace = Marketplace.all
    end
    
    def team
    
    end

    def post
        newpost = Blog.new
        newpost.name = params[:name]
        newpost.text = params[:text]
        newpost.save
        redirect_to "/blog"
    end

    def blog
        @blog = Blog.last(3)
    end
    
    def test
        @name = "Testing Calls"
        @cats = Cat.all
        
        newcat = Cat.new
        newcat.name = params[:name]
        newcat.weight = params[:weight]
        newcat.color = params[:color]

        newcat.save
        #redirect_to "/test"
    end

    def login
        @name = params[:username]
        @allowed = false
        if params[:password]=='123asd' #password in parentheses
                @allowed=true
        end
    end

    def admin
        @marketplace = Marketplace.all
    end

    def newproduct
        @marketplace = Marketplace.all
        
        newproduct = Marketplace.new
        newproduct.image = params[:image]
        newproduct.name = params[:name]
        newproduct.price = params[:price]
        newproduct.description = params[:description]
        newproduct.quantity = params[:quantity]

        newproduct.save
        redirect_to "/admin"
    end
  

end

app/controllers/product_controller.rb
class ProductController < ApplicationController
	# make sure the cart cookie is initialized
	before_action :initialize_cart
  
	# GET /products
	def index
	  # the front page of the store
	  @products = Marketplace.all
	end
  
	def api
	  @products = Marketplace.all
	  render json: @products and return
	end
  
  
	# POST /products/:id/buy
	def add_to_cart
	  # add the selected item to the cart cookie
	  session[:cart][params[:id]]+=1
	  @item_count += 1
	  puts session[:cart]
	  flash[:notice] = "item added to cart"
	  redirect_to storefront_url
	end
  
	# GET /products/cart
	def view_cart
	  # show the shopping cart
	  @items = @cart
		.filter{|id,count| count>0}
		.map{|id,count| [Marketplace.find(id),count]}
	end
  
	# GET /products/checkout
	def checkout
	  # this action should process the order
	  # instead we are just clearing the cart :)
	  session[:cart] = nil
	  # update the quantity remaining
	  @cart
		.filter{|id,count| count>0}
		.each do |id,count|
		  p = Marketplace.find(id)
		  p.quantity = [0,p.quantity-count].max
		  p.save
		end
	  flash[:notice] = "Your order is on the way!"
	  redirect_to root_path
	end
  
	private
	def initialize_cart
	  empty_cart = Marketplace.all.map{|p| [p.id.to_s, 0]}.to_h
	  session[:cart] ||= empty_cart
	  @cart = session[:cart]
	  @item_count = @cart.values.reduce(:+)
	end
  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
		@user = User.find_by(username: params[:username])

		if !!@user && @user.authenticate(params[:password])
			session[:user_id] = @user.id
			redirect_to user_path
		else
			message = "Something went wrong! Make sure your username and password are correct"
			redirect_to login_path, notice: message
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@users = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to root_path
		else
			render :newend
		end
	end

	def show
		@user = User.find(params[:id])
	end

	private

	def user_params
		params.require(:user).permit(:username, :password)
	end
	




end

app/helpers/application_helper.rb
module ApplicationHelper
	def logged_in?
		!!session[:user_id]
	end

	def current_user
		@current_user ||= User.find_by_id(session[:user_id]) if !!session[:user_id]
	end
	
end

app/helpers/home_helper.rb
module HomeHelper

end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/admin.html.erb
<%= stylesheet_link_tag "test.css" %>
<h1>
    Admin Page
</h1>

<h3>Here is where all admin requests will take place.</h3>
    

<p>Here are the items:</p>
<ul>
<% @marketplace.each do |market| %>
<li><%= market[:name]  %></li>
<% end %>
</ul>

<hr/>

<h2>Add a new Product</h2>



<form action='/newproduct' method='POST'>

<input name='image' type='text' placeholder='image.jpg'>
<input name='name' type='text' placeholder='name'>
<input name="price" type="decimal" placeholder='price'>
<input name="description" type="text" placeholder='description'>
<input name="quantity" type="number" placeholder='quantity'>
<input type='submit'>
</form>


<hr/>

<p class="dir"> 
	<a href="/">Home Site</a> &emsp;&emsp;
    <a href="/team">Team Site</a> &emsp;&emsp;
    <a href="/blog">Blog Site</a> &emsp;&emsp;
</p>








<hr/>

</form>

app/views/home/blog.html.erb
<%= stylesheet_link_tag "index.css" %>

<h1>
    Blog Page
</h1>

<hr>

<% @blog.each do |blog|  %>
    <h5><u><%= blog.name %></u>:&emsp;</h5>
    <p class="blog">
        <%= blog.text %>
    </p>

<%end%>

<form action='/post' method='POST'>

    <input name='name' type='text' placeholder='Name'>
    <input name="text" type="numtextber" placeholder='Write here'>  
    <input type='submit'>

</form>


<p>
    <a href="team">Team Site</a>
</p>
<p>
    <a href="/">Home Site</a>
</p>

app/views/home/index.html.erb
<head>
    <title>Index</title>
    <%= stylesheet_link_tag "index.css" %>
</head>

<body>
    <h1>
        Home Page
    </h1>

    <table>
        <tbody>
        <tr>
            <th>Image</th>
            <th>Name</th>
            <th>Price</th>
            <th>Description</th>
            <th>Quantity</th>
        </tr>
        <% @marketplace.each do |market| %>
            <tr>
                <td> <%= image_tag market[:image] %> </td>
                <td> <%= market[:name] %> </td>
                <td> <%= number_to_currency market[:price] %> </td>
                <td> <%= market[:description] %> </td>
                <td> <%= market[:quantity] %> </td>
            </tr>
        <%end%>
        </tbody>
    </table>
    <p > 
        <a href="/team">Team Site</a> &emsp;&emsp;
        <a href="/blog">Blog Site</a> &emsp;&emsp;
        <%= link_to "Store Site", storefront_path %> &emsp;&emsp;
        <%= link_to "View Cart", view_cart_path %> &emsp;&emsp;
        <a href="https://www.youtube.com/watch?v=xvFZjo5PgG0">The Best Site</a>
    </p>
</body>

app/views/home/login.html.erb
<h1>
This is the login page.
</h1>

app/views/home/team.html.erb
<html>

<head>
    <title>Team</title>
    <%= stylesheet_link_tag "index.css" %>
</head>

<body>
    <h1>
        Team Page
    </h1>
        <table>
            <tr><td><%= image_tag "Billy.jpg" %></td></tr>
            <tr><td>Billy</td></tr>
            <tr><td>Marketing</td></tr>
    </table>
    <table>
            <tr><td><%= image_tag "Bob.jpg" %></td></tr>
            <tr><td>Bob</td></tr>
            <tr><td>Design</td></tr>
    </table>
    <table>
            <tr><td><%= image_tag "Joe.jpg" %></td></tr>
            <tr><td>Joe</td></tr>
            <tr><td>Customer Service</td></tr>
    </table>    
    <p>
        <%= link_to "Blog Site", "/blog" %>&emsp;&emsp;
        <a href="/">Home Site</a>
    </p>
</body>

</html>

app/views/home/test.html.erb
<%= stylesheet_link_tag "test.css" %>
<h1>
    Test Page
</h1>

<p> This is how to pull things from ruby: <%= @name %> </p>
    
<ul>
<% @cats.each do |variable| %>
<li> <b><%= variable[:name]  %></b>, <%=  variable[:weight] %> </li>
<% end %>
</ul>
<% if @cats.length > 2 %>
<h2> Wow thats a lot of cats!</h2>
<%end%>

<table>
    <tbody>
        <% @cats.each do |cat| %>
        <tr>
            <td><%= cat.name %></td>
            <td><%= cat.weight %></td>
            <td><%= cat.color %></td>
        </tr>
        <% end %>
    </tbody>
</table>


<p class="dir"> 
    <a href="/team">Team Site</a> &emsp;&emsp;
    <a href="/blog">Blog Site</a> &emsp;&emsp;
    <a href="https://www.youtube.com/watch?v=xvFZjo5PgG0">The Best Site</a>
</p>

<hr/>

<h2>Add a new Cat</h2>



<form action='/cats' method='POST'>

<input name='name' type='text' placeholder='name'>
<input name="weight" type="number" placeholder='weight'>
<input name="color" type="text" placeholder='color'>
<input type='submit'>

</form>







<hr/>


<form action='/login' method='POST'>

<label>Username: </label>
<input name='username' type='text' placeholder='username'>
<label>Password: </label>
<input name="password" type="password">
<input type='submit'>

</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Webstore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="http://cdn.bootstrap">
    
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/product/index.html.erb
<!-- cart banner -->
<% if @item_count >0%>
  <div class="alert alert-primary">
    You have <%=pluralize(@item_count,"item")%> in your cart &mdash; <%= link_to "Checkout", view_cart_path %>
  </div>
<% end %>

<!-- flash message -->
<% if flash[:notice] %>
    <div class="alert alert-success"> <%= flash[:notice]%> </div>
<% end %>

<!-- product listing -->
<div class="row">
<% @products.each do |product| %>
<div class="card m-2" style="width: 18rem; background-color: #efe4b07a">
  <!-- product image -->
  <%= image_tag product.image, class: "card-img-top rounded mt-2" %>
  <br>
  <!-- quantity available -->
  <% if product.quantity == 0 %>
    <span class="badge bg-danger">sold out</span>
  <% elsif product.quantity < 3 %>
    <span class="badge bg-warning">only <%= product.quantity %> left! </span>
  <% else %>
    <span class="badge bg-secondary"><%= product.quantity %> available </span>
  <% end %>
  <!-- title, price, and description -->
  <div class="card-body">
    <h5 class="card-title"><%= product.name%>: <%=number_to_currency product.price%></h5>
    <p class="card-text"><%= product.description%></p>
    <!-- buy button -->
    <% if product.quantity > 0 %>
      <%= link_to "Add To Cart", add_to_cart_path(product), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
<% end %>
</div>

<br>
<%=link_to "Home", "/" %>

app/views/product/view_cart.html.erb
<h1>Your Cart</h1>
<% if @cart.empty? %>
    <h2>There is nothing in your cart!</h2>
<% else %>

<ul>
<% @items.each do |product, count| %>
    <li><%= pluralize(count, product.name) %></li>
<% end %>
</ul>
<%=link_to "Checkout", checkout_path, class: "btn btn-primary"%>
<% end %>
<hr/>
<%=link_to "Keep Shopping", "/products" %>

app/views/users/new.html.erb
<h1>New Users Page</h1>

<%= form_for @user do |f| %>
	<%= f.label :username %>
	<%= f.text_field :username %>
	<%= f.label :password %>
	<%= f.password_field :password %>
	<%= f.submit "Create Account" %>
<% end %>
	